[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/graph"
  to = "/.netlify/functions/graph"
  status = 200

[[redirects]]
  from = "/ask"
  to = "/.netlify/functions/ask"
  status = 200

[[redirects]]
  from = "/.netlify/functions/node"
  to = "/.netlify/functions/node"
  status = 200

[[redirects]]
  from = "/.netlify/functions/askNode"
  to = "/.netlify/functions/askNode"
  status = 200
